# change the build directory to be within react's scope


# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: feature estate ten fence speed math tube flavor pepper program chef harbor
      # mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
